const DEFAULT_ACHIEVEMENTS = [
  {
    type: 'learning',
    title: '初次记录',
    description: '完成第一条学习记录',
    icon: '⭐',
    condition: { type: 'count', target: 1 },
    isHidden: false,
  },
  {
    type: 'learning',
    title: '学习达人',
    description: '累计完成10条学习记录',
    icon: '🏆',
    condition: { type: 'count', target: 10 },
    isHidden: false,
  },
  {
    type: 'learning',
    title: '数学小达人',
    description: '数学全对累计10次',
    icon: '📐',
    condition: { type: 'count', subjectFilter: '数学', target: 10 },
    isHidden: false,
  },
  {
    type: 'persistence',
    title: '连续7天',
    description: '连续7天有学习记录',
    icon: '🔥',
    condition: { type: 'streak', target: 7 },
    isHidden: false,
  },
  {
    type: 'persistence',
    title: '连续30天',
    description: '连续30天有学习记录',
    icon: '💪',
    condition: { type: 'streak', target: 30 },
    isHidden: false,
  },
  {
    type: 'persistence',
    title: '连续100天',
    description: '连续100天有学习记录',
    icon: '👑',
    condition: { type: 'streak', target: 100 },
    isHidden: true,
  },
  {
    type: 'pet',
    title: '宠物达到10级',
    description: '任一宠物达到10级',
    icon: '🐉',
    condition: { type: 'pet_level', target: 10 },
    isHidden: false,
  },
  {
    type: 'pet',
    title: '宠物收藏家',
    description: '拥有3只宠物',
    icon: '🐾',
    condition: { type: 'pet_count', target: 3 },
    isHidden: true,
  },
  {
    type: 'learning',
    title: '全科之星',
    description: '一周内每科都有记录',
    icon: '🌟',
    condition: { type: 'all_subjects', target: 1 },
    isHidden: false,
  },
];

module.exports = { DEFAULT_ACHIEVEMENTS };
